#!/bin/sh
# Renders the fonts of the LVGL interface into src/fonts, see tools/fonts/README.md.
#
#   tools/mkfonts.sh
#
# Needs Node.js for npx lv_font_conv on the host, not in the image.
set -e
cd "$(dirname "$0")/.."

# DejaVu Sans: ASCII and Latin-1 for the English texts, typographic punctuation, arrows and a few symbols
# (check, cross, warning, play).
TEXT="0x20-0x7E,0xA0-0xFF,0x2013-0x2014,0x2018-0x201A,0x201C-0x201E,0x2022,0x2026,0x2190-0x2193,0x2713,0x2717,0x26A0,0x25B6"
# Font Awesome icons of the steps: house, sliders, hard-drive, network-wired, download, flag-checkered,
# check, circle-info.
ICONS="0xF015,0xF1DE,0xF0A0,0xF6FF,0xF019,0xF11E,0xF00C,0xF05A"

mkdir -p src/fonts
for size in 14 16 18 20 24 28 32; do
	npx -y lv_font_conv --bpp 4 --size "$size" --format lvgl \
		--font tools/fonts/DejaVuSans.ttf -r "$TEXT" \
		--font tools/fonts/fontawesome/fa-solid-900.ttf -r "$ICONS" \
		--lv-include lvgl.h --lv-font-name "wizard_font_$size" -o "src/fonts/wizard_font_$size.c.tmp"
	{
		echo "/* Generated by tools/mkfonts.sh, do not edit. Rendered from DejaVu Sans 2.37"
		echo " * (Bitstream Vera and Arev licenses, tools/fonts/DejaVuSans-LICENSE.txt) and icons of"
		echo " * Font Awesome 7.3.1 Free Solid (SIL OFL 1.1, tools/fonts/fontawesome/LICENSE.txt). */"
		sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' "src/fonts/wizard_font_$size.c.tmp"  # Without the empty lines at the end.
	} > "src/fonts/wizard_font_$size.c"
	rm "src/fonts/wizard_font_$size.c.tmp"
done
