#!/usr/bin/env python3
# Writes the licenses the About page shows into include/licenses.h.
#
#   tools/mklicenses.py

from os.path import dirname, join

ROOT = join(dirname(__file__), "..")
# Name, what it is in the wizard, license, file with the full text.
LICENSES = (
	("OE-Alliance SmallBox Wizard", "this application", "GPL-3.0", "LICENSE"),
	("LVGL 9.6.0", "the graphics library", "MIT", "lib/lvgl/LICENCE.txt"),
	("DejaVu Sans 2.37", "the font", "Bitstream Vera, Arev", "tools/fonts/DejaVuSans-LICENSE.txt"),
	("Font Awesome 7.3.1 Free", "the icons", "SIL OFL 1.1", "tools/fonts/fontawesome/LICENSE.txt"),
)


def literal(text):
	lines = []
	for line in text.replace("\r\n", "\n").rstrip("\n").split("\n"):
		line = line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "    ")
		lines.append('\t"%s\\n"' % line)
	return "\n".join(lines)


def main():
	out = ["/* Generated by tools/mklicenses.py, do not edit. */", "", "struct license {", "\tconst char *name;",
		"\tconst char *role;", "\tconst char *license;", "\tconst char *text;", "};", "",
		"static const struct license licenses[] = {"]
	for name, role, license, path in LICENSES:
		with open(join(ROOT, path), encoding="utf-8") as fd:
			text = fd.read()
		out.append('{"%s", "%s", "%s",\n%s},' % (name, role, license, literal(text)))
	out.append("};")
	with open(join(ROOT, "include", "licenses.h"), "w", encoding="utf-8", newline="\n") as fd:
		fd.write("\n".join(out) + "\n")


if __name__ == "__main__":
	main()
